# Generated by Django 2.2.13 on 2020-07-02 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_real_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_stu_num', models.IntegerField(blank=True, null=True)),
                ('user_phone', models.IntegerField(blank=True, null=True)),
                ('user_desc', models.TextField(blank=True, null=True)),
                ('is_approval', models.IntegerField(choices=[(-2, '拒绝注册'), (-1, '停用'), (0, '待通过'), (1, '注册通过')])),
                ('is_manager', models.IntegerField()),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'user_profile',
                'permissions': (('view_user_profile', 'View User Profile'), ('modify_user_profile', 'Modify User Profile'), ('can_approval_user', 'Can approval user')),
            },
        ),
    ]
